-- Insert sample stocks
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('AAPL', 180.50);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('GOOGL', 2750.75);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('AMZN', 3400.00);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('MSFT', 320.30);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('TSLA', 850.25);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('NFLX', 500.60);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('NVDA', 890.00);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('META', 340.40);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('IBM', 145.20);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('ORCL', 110.85);

-- Insert sample user portfolios
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JohnDoe', 'AAPL', 10, 1805.00);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JohnDoe', 'TSLA', 5, 4251.25);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JohnDoe', 'GOOGL', 3, 8252.25);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JohnDoe', 'AMZN', 2, 6800.00);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JohnDoe', 'META', 4, 1361.60);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JaneDoe', 'GOOGL', 3, 8252.25);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JaneDoe', 'AMZN', 2, 6800.00);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('Alice', 'MSFT', 8, 2562.40);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('Alice', 'META', 4, 1361.60);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('Bob', 'NVDA', 6, 5340.00);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('Bob', 'IBM', 10, 1452.00);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('Charlie', 'NFLX', 5, 2503.00);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('Charlie', 'ORCL', 12, 1330.20);