-- Insert sample stocks
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('AAPL', 180.50);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('GOOGL', 2750.75);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('AMZN', 3400.00);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('MSFT', 320.30);
INSERT INTO STOCK (SYMBOL, PRICE) VALUES ('TSLA', 850.25);

-- Insert sample user portfolios (with totalInvestment calculated)
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JohnDoe', 'AAPL', 10, 1805.00);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JohnDoe', 'TSLA', 5, 4251.25);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JaneDoe', 'GOOGL', 3, 8252.25);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('JaneDoe', 'AMZN', 2, 6800.00);
INSERT INTO PORTFOLIO ("USERNAME", STOCK_SYMBOL, QUANTITY, TOTAL_INVESTMENT) VALUES ('Alice', 'MSFT', 8, 2562.40);
